### ISSUE TITLE
Inconsistent snapshot behavior

### ISSUE THREAD

**Issue by pachacamac** [macadev/Gibbon-Tabs#1]
creating a tab snapshot with multiple windows open saves tabs from all browser windows but when restoring the snapshot it restores all tabs into only one single browser window.

personally I would prefer that the scope for creating snapshots would be only the current browser window, then the restoring behavior could also stay like it is.

**Comment by macadev** [comment]
Hey @pachacamac, thanks for the feedback! This is a great suggestion. I'll look into making this the default behaviour.

**Comment by macadev** [comment]
Latest commit implements this. It's pretty awesome - thanks for the suggestion!

I've made it so that legacy tab snapshots are still functional, so you don't have to delete the ones you have currently saved. 👍 

- Dan.

**Comment by macadev** [comment]
Update going out now. New feature should be live in 1 hour.

**Comment by pachacamac** [comment]
Progress! But not quite as I hoped :)

**Situation:** You have 3 windows with 10, 20 and 30 tabs respectively. In any window you create a snapshot. Snapshot now contains 60 tabs. You restore the snapshot. It restores all 3 windows with 10, 20 and 30 tabs. So definitely consistent now!

**What I thought:** You have 3 windows with 10, 20 and 30 tabs respectively. You create a snapshot in window A. Snapshot contains 10 tabs. You restore that snapshot, it opens one new window with those 10 tabs. You create a snapshot in window B. Snapshot contains 20 tabs. You restore that snapshot, it opens one new window with those 20 tabs. Etc. Maybe this could be done via an extra button? "Snapshot current window" & "Snapshot all windows"?

**Comment by macadev** [comment]
Damn hahahaha, I missed this behaviour in your description. It should be an easy fix, and I think it's worth giving users this level of flexibility. I'll work on it soon.

**Comment by macadev** [comment]
This update will be going out soon! :)

<img width="610" alt="screen shot 2017-05-06 at 2 42 07 pm" src="https://cloud.githubusercontent.com/assets/6581226/25775059/35d2ff72-326a-11e7-8c23-b75e3b08fa6d.png">

**Comment by macadev** [comment]
Update going out now. It also includes snapshot synchronization across all your devices! Please try it out and let me know what you think.

Also, I made it so you won't have your current snapshots deleted. The code still supports your legacy snapshots - these should also be synchronized across all your devices.
