### ISSUE TITLE
Feature Request: Restricting search space to current window

### ISSUE THREAD

**Issue by ShivanKaul** [macadev/Gibbon-Tabs#11]
Hi again! 

I'd love the ability to search *only* the current Chrome window. My use case is that on my work laptop I'm signed into my work Gmail/Keep/Drive/etc and I have an incognito window open where I'm signed into my personal accounts. However, when I want to search for Gmail, it's not clear from the search options which one is which. Maybe even if the search suggestion had the text or badge "current window" next to it, that would be helpful. 

As always, thanks for your effort!

**Comment by macadev** [comment]
That sounds awesome! I'll build it.

**Comment by macadev** [comment]
This has been built and released today! I ended up adding a small icon to the tabs that are on the current window.

Thanks for the great feature idea!
