### ISSUE TITLE
The window icons overlap the close icons when hovering over a specific tab.

### ISSUE THREAD

**Issue by diegomacario** [macadev/Gibbon-Tabs#12]
Yaaaaaaaaaaas queeeeeeen, the new feature is sooooooo helpful! But there is a minor UI problem: the new icons overlap the close icons when hovering over a specific tab (please see the image below).

![windowiconoverlapsxicon](https://user-images.githubusercontent.com/8304271/42517646-33b5f318-842e-11e8-9306-6731e9de6edb.PNG)

Keep it real dander-falls-waterfalls.

De'Angers

**Comment by diegomacario** [comment]
Here is an updated image for more clarity:

**Comment by diegomacario** [comment]
Whoopsie daisy I accidentally closed this bug because I spilled some coffee on my pants. I have reopened it.

De'Angers

**Comment by macadev** [comment]
Dear overly-enthusiastic Gibbon Tabs user #1,

Issue will be fixed asap or I'll spill coffee on my pants as punishment.

-- Dandy

**Comment by macadev** [comment]
My child,

The CSS bug should now be gone. You should see the extension version go up to 1.1.2. Check the chrome://extensions page to see your current version.

Thanks for reporting this vicious UX bug. It breaks my heart seeing my spaghetti CSS not be parsed correctly.

ps. to future employers: yes, the CSS in this project is terrible. However, I am a much gooder engineer now. Gibbon Tabs has over 300 users. It is loved by many!

**Comment by diegomacario** [comment]
My baby-faced son,

Thank you for fixing this problem!!! Gibbon Tabs is indeed loved by many.

P.S. For all future employers:

I can attest to Denial's skills. Through our 4 years at McGill University, he single-handedly carried dozens of lazy engineers on his back and got them to graduate. True story. Ask anyone.

Diaggio Enrico Marzelo Bellafonte, Arch-Duke of the International House of Pancakes

**Comment by macadev** [comment]
Well pretty-faced-baby-man,

Thanks for your compliment, but that is most certainly not true. Instant Nescafé™ coffee carried my soul, and thus everyone with me.

-- Dandy the Second son of Dr. Oetker's Ristorante frozen-pizzas, descendant of Lord Nescafe™-Cremanata.
