### ISSUE TITLE
Update snapshots

### ISSUE THREAD

**Issue by pachacamac** [macadev/Gibbon-Tabs#2]
Would also be nice to be able to update/edit snapshots. Like remove single tabs from a snapshot or add single tabs to a snapshot so "collections" like "my apartment search" or "my research on x" can be maintained and don't remain frozen. If #1 this one are implemented this would be the perfect tab manager for me I think :)

**Comment by macadev** [comment]
Also a great idea, I'll try to design a little widget for this.

**Comment by pachacamac** [comment]
Thought of a simple way to do this without a new widget: How about when you save a snapshot you simply can select an existing one to overwrite? This way editing a snapshot would simply be:

* open existing snapshot
* make adaptions (close tabs, add tabs, rearrange tabs)
* save snapshot, selecting existing snapshot

**Comment by macadev** [comment]
Woah that is so simple, and it will do the trick. I'll look into building it soon!

**Comment by pachacamac** [comment]
Any progress? :grin:

**Comment by macadev** [comment]
@pachacamac I've been very busy with work lately. It's finally looking like I'll get some time back. I'll  resume working on this feature this week!

**Comment by macadev** [comment]
Current working on this! Update will hopefully go out today!

**Comment by macadev** [comment]
That's it! The update is going out right now. Please let me know if you encounter any issues @pachacamac! :)

**Comment by pachacamac** [comment]
Sorry for late response, also overly busy with work lately. Works like a charm though! Thanks for this update! Super helpful :)
