### ISSUE TITLE
Configurable key for closing tabs (like Delete for windows users)

### ISSUE THREAD

**Issue by bendtherules** [macadev/Gibbon-Tabs#5]

**Comment by macadev** [comment]
Hey @bendtherules, there is currently a shortcut just for this. You can press shift + backspace to delete the currently highlighted tab in the list. You're saying you would prefer to be able to modify this shortcut to a custom one? Let me know

**Comment by bendtherules** [comment]
Yes. Shift + Backspace doesn't seem to work right now in Chrome on OSX.
Something like a single key shortcut will be helpful (like Delete in OSX and just Backspace in Windows). Or, maybe better yet, if it is configurable, anyone can just suit themselves.

In my head, it would work really nice with #4, where you can start with the current tab and aggresively close many tabs including this one. Its better than just multiple Ctrl+W as I get to see the page title before closing and switching to new tab takes some time to load on slower machines.

**Comment by macadev** [comment]
Oh that's pretty strange, I'm also running Chrome on OSX and it works for me. I'll investigate this further and get back to you.

**Comment by macadev** [comment]
Hi @bendtherules, is the delete shortcut working for you now?

**Comment by bendtherules** [comment]
I have Version 1.0.6 from Chrome store  and delete or fn+delete, none of it
closes the tab.

**Comment by macadev** [comment]
@bendtherules could you try pressing "Shift" + "backspace" while you have have the extension open and have open tabs shown? "fn" + "delete" isn't a shortcut yet. 

The "backspace" key on its own is used to delete the search queries, so I can't make it the default "Delete tab" shortcut.

Thanks for the help!

**Comment by bendtherules** [comment]
"Shift" + "backspace" also doesnt work

**Comment by bendtherules** [comment]
Sorry, it is actually working. Was not working because of another
key-remapping application.

**Comment by macadev** [comment]
I'll close the issue then :)

I'm planning to add a little popup "How to use" menu to the extension to clear up doubts like these.

Thanks for using the extension!
