### ISSUE TITLE
[Question] Are  snapshots saved in chrome "cloud space" so that it can be restored on different devices?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [macadev/Gibbon-Tabs#7]
Hello, sorry for creating an issue out of this.
I'm looking to replace 2 plugins I have: one that includes saving tabs across my chrome devices and one that allows searching.

This solves the searching quite well, but from my understanding it doesn't save in chrome cloud space, so I can't restore snapshots from different devices. Is this correct?

**Comment by macadev** [comment]
Hey @Fire-Dragon-DoL, at the moment the extension stores snapshots locally. By early next week I'll push an update that will allow the snapshots to be stored on the cloud using Google's chrome.sync. Like you said, this means the snapshots will be available across all your devices! :)

**Comment by Fire-Dragon-DoL** [comment]
OK! Thanks a lot ;)

**Comment by macadev** [comment]
This has now been implemented, and the update is out! Your snapshots are synced across all your devices running Chrome!

**Comment by Fire-Dragon-DoL** [comment]
Thanks that's lovely!!!
