### ISSUE TITLE
unable to restore snapshots

### ISSUE THREAD

**Issue by pachacamac** [macadev/Gibbon-Tabs#8]
Hey there, just tried out your new version (1.06) and while I see the new option to save snapshots for active- and all windows and the save shows "success", when I click on the restore snapshot button, nothing happens. I inspected the popup and the console shows the following error message:

    Error in response to storage.get: TypeError: Cannot read property 'uid' of undefined
    at chrome-extension://bmkakdcikgcicahfkmcehpbhidhccfld/js/snapshot.js:265:78
    at Object.callback (chrome-extension://bmkakdcikgcicahfkmcehpbhidhccfld/js/snapshot.js:51:7)
    at getSnapshot (chrome-extension://bmkakdcikgcicahfkmcehpbhidhccfld/js/snapshot.js:45:23)
    at Object.callback (chrome-extension://bmkakdcikgcicahfkmcehpbhidhccfld/js/snapshot.js:49:7)

**Comment by macadev** [comment]
Hey @pachacamac, did you have any old snapshots that carried over to the newer version? I think something I didn't account for might have corrupted the data you've stored. I'll try to replicate and fix the issue so it doesn't happen to other users. In the meantime, if you want the extension to work again delete it by going to chrome://extensions and then reinstall it. That should clear your stored snapshots.

Sorry for the inconvenience! I hope this isn't happening to a lot of users.

**Comment by pachacamac** [comment]
Thanks. Yes that was the case. Works after fresh install

**Comment by macadev** [comment]
Hi @pachacamac, I've decided to close this issue. By now the legacy code for restoring old snapshots is probably not getting hit anymore, so I don't think anyone is impacted by this anymore.

**Comment by pachacamac** [comment]
Makes sense.
